server:
  port: 8083

spring:
  application:
    name: grpc-service-demo
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://testup8.c2jfdgtlpko2.us-east-2.rds.amazonaws.com:3306/brio?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: brio
    password: 1qaz!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 1500000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: DatebookHikariCP
      validation-timeout: 5000
    type: com.zaxxer.hikari.HikariDataSource

  ## redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    timeout: 300
    lettuce:
      pool:
        max-active: 2
        max-idle: 2
        max-wait: 3000ms
        min-idle: 2
      shutdown-timeout: 100ms