// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zdto.proto

package com.mylomen.grpc.pb;

public interface ComReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_base.ComReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string target = 2;</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 2;</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <code>string method = 3;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 3;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>bytes headers = 4;</code>
   * @return The headers.
   */
  com.google.protobuf.ByteString getHeaders();

  /**
   * <code>bytes body = 5;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
