// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zdto.proto

package com.mylomen.grpc.pb;

public final class GrpcCommon {
  private GrpcCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_base_ComReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_base_ComReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_base_ByteResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_base_ByteResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nzdto.proto\022\010api_base\032\034google/api/annot" +
      "ations.proto\"S\n\006ComReq\022\n\n\002id\030\001 \001(\003\022\016\n\006ta" +
      "rget\030\002 \001(\t\022\016\n\006method\030\003 \001(\t\022\017\n\007headers\030\004 " +
      "\001(\014\022\014\n\004body\030\005 \001(\014\"5\n\nByteResult\022\014\n\004code\030" +
      "\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\014\n\004data\030\003 \001(\0142a\n\013Base" +
      "Service\022R\n\007execute\022\020.api_base.ComReq\032\024.a" +
      "pi_base.ByteResult\"\037\202\323\344\223\002\031\"\024/rpc/v1/base" +
      "/execute:\001*B#\n\023com.mylomen.grpc.pbB\nGrpc" +
      "CommonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_api_base_ComReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_base_ComReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_base_ComReq_descriptor,
        new java.lang.String[] { "Id", "Target", "Method", "Headers", "Body", });
    internal_static_api_base_ByteResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_base_ByteResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_base_ByteResult_descriptor,
        new java.lang.String[] { "Code", "Msg", "Data", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
